import type { Metadata } from "next";
import { DM_Serif_Text } from 'next/font/google';
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


import Header from "./components/Header";


const dmSerif = DM_Serif_Text({
  weight: '400', // Only one weight available
  subsets: ['latin'],
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" /></head>
      <body className={`${dmSerif.className} with100`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
