import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


import Header from "./components/Header";


const ptSerif = PT_Serif({
  weight: ["400", "700"], // normal + bold
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" /></head>
      <body className={`${ptSerif.className} `}>
        
        {children}
      </body>
    </html>
  );
}
            